# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Elección',
                'verbose_name_plural': 'Elecciones',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
            options={
                'verbose_name': 'Mesa de votación',
                'verbose_name_plural': 'Mesas de votación',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('list_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.List')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.PollingStation')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
            options={
                'verbose_name': 'Votante',
                'verbose_name_plural': 'Votantes',
            },
        ),
        migrations.CreateModel(
            name='VotingJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.PollingStation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jurado de votación',
                'verbose_name_plural': 'Jurados de votación',
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.Voter'),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set([('document', 'election')]),
        ),
    ]
