# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.PollingStation')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.Voter')),
            ],
        ),
    ]
