# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
