# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
    ]
