# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20170922_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set([('document', 'election')]),
        ),
    ]
