# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20170922_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
            ],
            options={
                'verbose_name': 'Mesa de votación',
                'verbose_name_plural': 'Mesas de votación',
            },
        ),
    ]
